// GENERATED by scripts/prepare-assets.mjs — do not edit by hand.
export type MediaSize = { w: number; h: number; duration?: number };

export const media = {
  "films": {
    "dormant-estate": {
      "w": 1280,
      "h": 720,
      "duration": 4
    },
    "discovery-sweep": {
      "w": 1280,
      "h": 720,
      "duration": 4
    },
    "fleet-activation": {
      "w": 1280,
      "h": 720,
      "duration": 4
    },
    "flow-and-fracture": {
      "w": 1280,
      "h": 720,
      "duration": 4
    },
    "governed-release": {
      "w": 1280,
      "h": 720,
      "duration": 4
    },
    "completion": {
      "w": 1280,
      "h": 720,
      "duration": 4
    },
    "agent-fleet": {
      "w": 1920,
      "h": 1080,
      "duration": 8
    },
    "problem-solution": {
      "w": 1280,
      "h": 720,
      "duration": 10
    }
  },
  "shots": {
    "1": {
      "w": 1917,
      "h": 931
    },
    "2": {
      "w": 1917,
      "h": 926
    },
    "4": {
      "w": 1917,
      "h": 927
    },
    "5": {
      "w": 1917,
      "h": 926
    },
    "6": {
      "w": 1917,
      "h": 927
    },
    "9": {
      "w": 1917,
      "h": 930
    },
    "10": {
      "w": 1917,
      "h": 935
    },
    "13": {
      "w": 1917,
      "h": 927
    },
    "14": {
      "w": 1912,
      "h": 917
    },
    "15": {
      "w": 1916,
      "h": 925
    },
    "16": {
      "w": 1917,
      "h": 921
    },
    "17": {
      "w": 1917,
      "h": 927
    },
    "18": {
      "w": 1917,
      "h": 927
    },
    "11-0": {
      "w": 1917,
      "h": 920
    },
    "11-1": {
      "w": 1917,
      "h": 922
    },
    "11-2": {
      "w": 1917,
      "h": 927
    },
    "12-0": {
      "w": 1917,
      "h": 932
    },
    "12-1": {
      "w": 1917,
      "h": 925
    },
    "3-0": {
      "w": 1917,
      "h": 927
    },
    "3-1": {
      "w": 1275,
      "h": 622
    },
    "3-2": {
      "w": 1276,
      "h": 627
    },
    "3-3": {
      "w": 1272,
      "h": 627
    },
    "3-4": {
      "w": 1277,
      "h": 622
    },
    "3-5": {
      "w": 1276,
      "h": 617
    },
    "3-6": {
      "w": 1272,
      "h": 612
    },
    "7-0": {
      "w": 1917,
      "h": 927
    },
    "7-1": {
      "w": 1917,
      "h": 927
    },
    "7-2": {
      "w": 1917,
      "h": 927
    },
    "7-3": {
      "w": 1917,
      "h": 927
    },
    "7-4": {
      "w": 1917,
      "h": 920
    },
    "8-0": {
      "w": 1916,
      "h": 927
    },
    "8-1": {
      "w": 1917,
      "h": 922
    },
    "8-2": {
      "w": 1917,
      "h": 927
    }
  },
  "diagrams": {
    "01-whole-application-gcp-deployment": {
      "w": 3840,
      "h": 2160
    },
    "02-agent-fleet-capability-dispatch": {
      "w": 3840,
      "h": 2160
    },
    "03-orchestrator-state-machine": {
      "w": 3840,
      "h": 2160
    },
    "03b-orchestrator-event-routes": {
      "w": 3840,
      "h": 2160
    },
    "04-discovery-agent": {
      "w": 3840,
      "h": 2160
    },
    "05-lineage-agent": {
      "w": 3840,
      "h": 2160
    },
    "06-risk-compliance-agent": {
      "w": 3840,
      "h": 2160
    },
    "07-migration-planner-agent": {
      "w": 3840,
      "h": 2160
    },
    "08-validation-reconciliation-agent": {
      "w": 3840,
      "h": 2160
    },
    "09-cutover-agent": {
      "w": 3840,
      "h": 2160
    },
    "10-finance-impact-agent": {
      "w": 3840,
      "h": 2160
    },
    "11-reliability-idempotency-dlq": {
      "w": 3840,
      "h": 2160
    },
    "12-wwi-flagship-migration-sequence": {
      "w": 3200,
      "h": 3326
    }
  },
  "agents": {
    "cutover": {
      "w": 256,
      "h": 256
    },
    "discovery": {
      "w": 256,
      "h": 256
    },
    "finance-impact": {
      "w": 256,
      "h": 256
    },
    "lineage": {
      "w": 256,
      "h": 256
    },
    "planner": {
      "w": 256,
      "h": 256
    },
    "risk": {
      "w": 256,
      "h": 256
    },
    "validation": {
      "w": 256,
      "h": 256
    }
  },
  "empty": {
    "estate-onboarded": {
      "w": 256,
      "h": 256
    },
    "migration-complete": {
      "w": 256,
      "h": 256
    },
    "no-approvals": {
      "w": 256,
      "h": 256
    },
    "no-dead-letters": {
      "w": 256,
      "h": 256
    },
    "no-incidents": {
      "w": 256,
      "h": 256
    },
    "no-memory": {
      "w": 256,
      "h": 256
    },
    "no-policy-violations": {
      "w": 256,
      "h": 256
    },
    "no-runs": {
      "w": 256,
      "h": 256
    }
  },
  "brand": {
    "symbol": {
      "w": 512,
      "h": 512
    },
    "wordmark": {
      "w": 1200,
      "h": 499
    }
  },
  "sequences": {
    "problem-solution": {
      "frames": 96,
      "w": 1024,
      "h": 576,
      "duration": 10
    }
  },
  "team": {
    "mousmi": {
      "w": 900,
      "h": 1125
    },
    "nikhil": {
      "w": 600,
      "h": 750
    }
  }
} as const;

export type ShotKey = keyof typeof media.shots;
export type FilmKey = keyof typeof media.films;
export type SequenceKey = keyof typeof media.sequences;
